### ISSUE TITLE
not using GPU on HPC environment

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/kdl-vqa#8]
This may not be a bug with the tool itself.
When installing all the requirements and running the tool on the test folder with moondream, the GPU is not used.

**Comment by geoffroy-noel-ddh** [comment]
Error message below.

1. torch detects one CUDA device
2. but query for first device specs crashes
3. that error affects bvqa execution

```bash
kXXXXXX@erc-hpc-comp190:/scratch/users/kXXXXXX/kdl-vqa$ python -c "import torch; print(torch.cuda.device_count())"
1

>>> torch.cuda.get_device_properties(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/users/kXXXXXX/kdl-vqa/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 523, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "/scratch/users/kXXXXXX/kdl-vqa/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 319, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.


kXXXXXX@erc-hpc-comp190:/scratch/users/kXXXXXX/kdl-vqa$ python bvqa.py describe -r
  0%|                                                                      | 0/3 [00:00<?, ?it/s]/scratch/users/kXXXXXX/kdl-vqa/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
WARNING: running model on CPU
PhiForCausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
`get_max_cache()` is deprecated for all Cache classes. Use `get_max_cache_shape()` instead. Calling `get_max_cache()` will raise error from v4.48
100%|██████████████████████████████████████████████████████████████| 3/3 [02:33<00:00, 51.22s/it]
```

**Comment by geoffroy-noel-ddh** [comment]
Most likely explanation is that [compute node erc-hpc-comp190 has been reported as malfunctioning](https://forum.er.kcl.ac.uk/t/issue-with-comp190/2597). That node is the one I get by default when requesting an A30. When I pass `--exclude erc-hpc-comp190` to `srun` I get an alternative node with an A30 which works well with bvqa.

```bash
kXXXXXX@erc-hpc-comp196:/scratch/users/kXXXXXX/kdl-vqa$ python -c "import torch; print(torch.__version__); print(torch.cuda.is_available()); print([torch.cuda.get_device_properties(i) for i in range(torch.cuda.device_count())]);"
2.5.1+cu124
True
[_CudaDeviceProperties(name='NVIDIA A30', major=8, minor=0, total_memory=24062MB, multi_processor_count=56, uuid=e9514850-72a7-4c6e-a991-92a457f37aff, L2_cache_size=24MB)]
```
